using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;

namespace MSXUtilities
{
    class Program
    {
        /// <summary>
        /// MSX Utilities for homebrew game development
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
            //var command = "OUTI";
            //var number = 128;
            //var unrolledCommands = MakeUnrolledCommands(command, number);
            //return;

            //PocMegaROM();

            //ConvertColorTable();

            //NameTableWithOffset();

            //CalcPositionsPseudo3DEffect();

            //CreateTilesForPacific2()




            //CreateTilesForGoPenguin();

            // Create Tilemap for Go Penguin
            //var tileMap_16x16_Static = MSXUtilities.GoPenguin.TileMaps.TestLevel_1.TileMap_TestLevel_1.LoadTileMap();
            //var tileMap_16x16_Static = MSXUtilities.GoPenguin.TileMaps.TestLevel_2.TileMap_TestLevel_2.LoadTileMap();
            //GoPenguin.TileMaps.CreateTileMap.Execute(tileMap_16x16_Static);

            // Import tilemap from Tiled Map Editor
            //var Tiled_TileMapFilePath = @"C:\Users\albs_\OneDrive\Desktop\MSX development\GoPenguin\tile map test..csv";
            //var baseLabel = "BgObjectsInitialState_TestLevel_2";
            //var tilemapConverted = GoPenguin.TileMaps.ImportTileMapFromTiled.Execute(Tiled_TileMapFilePath, baseLabel);
            //GoPenguin.TileMaps.CreateTileMap.Execute(tilemapConverted);

            //// Convert bmp image into 16kb chunks to be used as background scroll on MSX 2
            //var image = @"C:\Users\albs_\OneDrive\Desktop\MSX development\Aero Fighters 3 screen tests\sonic wings ussr bg 304x990.png";
            ////var heightSc5 = (16 * 1024) / 128;  // 128 bytes per line (e.g. screen 5)
            //var heightSc8 = (16 * 1024) / 256;  // 256 bytes per line (e.g. screen 8)
            //SplitImageIn16KbChunks(image, heightSc8, "aerofighters-bg2");

            // Remove 7 byte header from file and keep only 16kb
            //var baseFileName = @"C:\Users\albs_\source\repos\msx-utilities\MSXUtilities\bin\Debug\netcoreapp3.1\aerofighters-bg2_{0}.sra";
            //RemoveHeaderAndKeep16kbOfFiles(baseFileName, 7);

            var fileName = @"C:\Users\albs_\OneDrive\Desktop\MSX development\Aero Fighters 3 screen tests\sprites.bak.sc5";
            ConvertSc5ImageToSprites(fileName);

            Console.WriteLine("Done.");
            Console.ReadLine();
        }

        /// <summary>
        /// Convert a .sc5 image file generated by BMP2MSX
        /// into a series of 16x16 sprites with 3 colors per line (OR-color)
        /// </summary>
        /// <param name="fileName"></param>
        private static void ConvertSc5ImageToSprites(string fileName)
        {
            const int HEADER_SIZE = 7; // 7 bytes header

            // get palette from file (last 32 bytes)
            byte[] paletteBytes = new byte[32];
            using (var input = File.OpenRead(fileName))
            using (BinaryReader reader = new BinaryReader(input))
            {
                reader.BaseStream.Seek(input.Length - 32, SeekOrigin.Begin);
                reader.Read(paletteBytes, 0, 32);
            }
            var palette = new List<List<int>>();
            for (int i = 0; i < 32; i += 2)
            {
                int red = (paletteBytes[i] & 0b11110000) >> 4;
                int blue = (paletteBytes[i] & 0b00001111);
                int green = paletteBytes[i + 1];

                palette.Add(new List<int> { red, blue, green });
            }
            // create a replacement color for each color of the palette (color most similar)
            var paletteReplacement = new List<int>();
            paletteReplacement.Add(-1); // first index is transperent color
            const int FIRST_COLOR = 1; // skip palette first entry (transperent)
            for (int i = FIRST_COLOR; i < 16; i++)
            {
                // calculate distance from this color to each other
                var distances = new List<int>();
                var smallestDistance = (7 + 7 + 7) + 1;
                var smallestDistanceIndex = 0;
                for (int j = FIRST_COLOR; j < 16; j++)
                {
                    if (i != j)
                    {
                        const int RED = 0;
                        const int BLUE = 1;
                        const int GREEN = 2;
                        var currentDistance =
                            Math.Abs(palette[i][RED] - palette[j][RED]) +
                            Math.Abs(palette[i][BLUE] - palette[j][BLUE]) +
                            Math.Abs(palette[i][GREEN] - palette[j][GREEN]);
                        distances.Add(currentDistance);

                        if (currentDistance < smallestDistance)
                        {
                            smallestDistance = currentDistance;
                            smallestDistanceIndex = j;
                        }
                        else if (currentDistance == smallestDistance)
                        {
                            // if two RGB distances are equal, the one with smaller individual distances should prevail
                            // Ex.: RGB distances (0, 2, 0) vs (1, 1, 0), the second one is the winner

                            //var distanceRed = Math.Abs(palette[i][RED] - palette[j][RED]) - Math.Abs(palette[i][RED] - palette[smallestDistanceIndex][RED]);
                            //var distanceBlue = Math.Abs(palette[i][BLUE] - palette[j][BLUE]) - Math.Abs(palette[i][BLUE] - palette[smallestDistanceIndex][BLUE]);
                            //var distanceGreen = Math.Abs(palette[i][GREEN] - palette[j][GREEN]) - Math.Abs(palette[i][GREEN] - palette[smallestDistanceIndex][GREEN]);

                            var distancesFromIToJ = new int[] {
                                Math.Abs(palette[i][RED] - palette[j][RED]),
                                Math.Abs(palette[i][BLUE] - palette[j][BLUE]),
                                Math.Abs(palette[i][GREEN] - palette[j][GREEN])
                            };

                            var distancesFromIToSmallest = new int[] {
                                Math.Abs(palette[i][RED] - palette[smallestDistanceIndex][RED]),
                                Math.Abs(palette[i][BLUE] - palette[smallestDistanceIndex][BLUE]),
                                Math.Abs(palette[i][GREEN] - palette[smallestDistanceIndex][GREEN])
                            };

                            if (Enumerable.Max(distancesFromIToJ) < Enumerable.Max(distancesFromIToSmallest))
                            {
                                //smallestDistance = currentDistance;
                                smallestDistanceIndex = j;
                            }

                            //if (Math.Abs(palette[i][RED] - palette[j][RED]) == Math.Abs(palette[i][RED] - palette[smallestDistanceIndex][RED]))
                            //{ 
                            //}


                            //Math.Abs(palette[i][BLUE] - palette[j][BLUE]) +
                            //Math.Abs(palette[i][GREEN] - palette[j][GREEN]);
                        }
                    }
                }

                // put the color most similar in the replacement array
                paletteReplacement.Add(smallestDistanceIndex);


            }

            using (var input = File.OpenRead(fileName))
            using (var reader = new BinaryReader(input))
            using (var output = File.Create(fileName + ".new"))
            {
                var counter = 0;
                IList<int> colorsList = new List<int>();
                //var pixelsList = new List<int>();
                var foundCounter = 0;
                var notFoundCounter = 0;
                for (int j = 0; j < input.Length; j++)
                {
                    var byteRead = reader.ReadByte();
                    if (j >= HEADER_SIZE) // skip header
                    {
                        var highNibble = byteRead & 0xf0;
                        var lowNibble = byteRead & 0b00001111;

                        var leftPixelColor = highNibble >> 4;
                        var rightPixelColor = lowNibble;

                        //if (leftPixelColor != 0 && !colorsList.Contains(leftPixelColor)) colorsList.Add(leftPixelColor);
                        //if (rightPixelColor != 0 && !colorsList.Contains(rightPixelColor)) colorsList.Add(rightPixelColor);

                        if (leftPixelColor != 0) colorsList.Add(leftPixelColor);
                        if (rightPixelColor != 0) colorsList.Add(rightPixelColor);

                        counter++;
                        if (counter == 8) // 8 bytes = 16 pixels on screen 5
                        {
                            var colorsGrouped = colorsList
                                .GroupBy(x => x)
                                .Select(n => new { ColorNumber = n.Key, Count = n.Count() })
                                .OrderByDescending(x => x.Count)
                                .ToList();

                            if (colorsGrouped.Count == 3)
                            {
                                var color1 = 0;
                                var color2 = 0;
                                var orColor = 0;
                                bool found = false;

                                found = CheckIfOrColorIsPossible(
                                    colorsGrouped[0].ColorNumber,
                                    colorsGrouped[1].ColorNumber,
                                    colorsGrouped[2].ColorNumber
                                    );

                                if (!found)
                                {
                                    // try again, replacing each color by a replacement candidate
                                    found = CheckIfOrColorIsPossible(
                                        paletteReplacement[colorsGrouped[0].ColorNumber],
                                        colorsGrouped[1].ColorNumber,
                                        colorsGrouped[2].ColorNumber
                                        );

                                    if (!found)
                                    {
                                        found = CheckIfOrColorIsPossible(
                                            colorsGrouped[0].ColorNumber,
                                            paletteReplacement[colorsGrouped[1].ColorNumber],
                                            colorsGrouped[2].ColorNumber
                                            );
                                    }

                                    if (!found)
                                    {
                                        found = CheckIfOrColorIsPossible(
                                            colorsGrouped[0].ColorNumber,
                                            colorsGrouped[1].ColorNumber,
                                            paletteReplacement[colorsGrouped[2].ColorNumber]
                                            );
                                    }

                                }

                                if (!found)
                                {
                                    notFoundCounter++;
                                }
                                else
                                {
                                    foundCounter++;
                                }
                            }
                            else if (colorsGrouped.Count > 3)
                            {
                                // loop from color with less repetitions upwards
                                // replacing by the others until find a combination
                                // valid to form 3 colors with OR-color
                                foreach (var item in colorsGrouped)
                                {

                                }
                            }

                            colorsList.Clear();
                            counter = 0;
                        }
                    }
                }

                //var buffer = new byte[4096 * 4]; // 16 kb page

                //// only one page
                //var actual = reader.Read(buffer, 0, buffer.Length);
                //output.Write(buffer, 0, actual);
            }
        }

        private static bool CheckIfOrColorIsPossible(int color0, int color1, int color2)
        {
            var or1 = color0 | color1;
            if (or1 == color2)
            {
                //color1 = colorsGrouped[0].ColorNumber;
                //color2 = colorsGrouped[1].ColorNumber;
                //orColor = colorsGrouped[2].ColorNumber;
                return true;
            }

            var or2 = color0 | color2;
            if (or2 == color1)
            {
                //color1 = colorsGrouped[0].ColorNumber;
                //color2 = colorsGrouped[1].ColorNumber;
                //orColor = colorsGrouped[2].ColorNumber;
                return true;
            }

            var or3 = color1 | color2;
            if (or3 == color0)
            {
                //color1 = colorsGrouped[0].ColorNumber;
                //color2 = colorsGrouped[1].ColorNumber;
                //orColor = colorsGrouped[2].ColorNumber;
                return true;
            }

            return false;
        }

        /// <summary>
        /// Remove the 7-byte header of file and keep only
        /// the following 16 kb, in order to fit one MegaROM page
        /// </summary>
        /// <param name="baseFileName"></param>
        /// <param name="skipBytes"></param>
        private static void RemoveHeaderAndKeep16kbOfFiles(string baseFileName, int skipBytes)
        {
            const int HEADER_SIZE = 7; // 7 bytes header
            for (int i = 0; i < 100; i++)
            {
                var fileName = String.Format(baseFileName, i);
                if (!File.Exists(fileName)) break;

                using (var input = File.OpenRead(fileName))
                using (var reader = new BinaryReader(input))
                using (var output = File.Create(fileName + ".new"))
                {
                    for (int j = 0; j < HEADER_SIZE; j++)
                    {
                        reader.ReadByte();
                    }

                    var buffer = new byte[4096 * 4]; // 16 kb page

                    // only one page
                    var actual = reader.Read(buffer, 0, buffer.Length);
                    output.Write(buffer, 0, actual);
                }
            }
        }


        /// <summary>
        /// Split image file in BMP format in smaller images that, when converted to MSX formats (.sc5, .sc8)
        /// will give 16 kb chunks to fit a Mega ROM page
        /// </summary>
        /// <param name="imageSourcePath"></param>
        /// <param name="height"></param>
        /// <param name="destinyBaseFilename"></param>
        private static void SplitImageIn16KbChunks(string imageSourcePath, int height, string destinyBaseFilename)
        {
            using (Bitmap bmpSource = new Bitmap(imageSourcePath))
            {
                if (bmpSource.Width < 256)
                {
                    throw new InvalidDataException("Source image should be at least 256 pixels wide");
                }

                int? lastImageNumber = null;
                Bitmap bmpDestiny = null;
                int yDest = 0;
                for (int y = 0; y < bmpSource.Height; y++)
                {
                    var currentImageNumber = ((int)(y / height));

                    if (lastImageNumber == null || lastImageNumber != currentImageNumber)
                    {
                        if (bmpDestiny != null)
                        {
                            bmpDestiny.Save(destinyBaseFilename + "_" + lastImageNumber + ".bmp", ImageFormat.Bmp);
                        }

                        lastImageNumber = currentImageNumber;
                        yDest = 0;

                        //height = ((bmpSource.Height - (currentImageNumber * height)) < height) ? (bmpSource.Height - (currentImageNumber * height)) : height;

                        bmpDestiny = new Bitmap(256, height);
                    }

                    for (int x = 0; x < 256; x++)
                    {
                        bmpDestiny.SetPixel(x, yDest, bmpSource.GetPixel(x, y));
                    }

                    yDest++;
                }
                bmpDestiny.Save(destinyBaseFilename + "_" + lastImageNumber + ".bmp", ImageFormat.Bmp);
            }
        }

        static void CreateTilesForGoPenguin()
        {
            var builder = new TilesForHorizontalScroll();


            IList<string> patternBgBlack = new List<string>();
            IList<string> colorBgBlack = new List<string>();

            IList<string> pattern_SmallBricks_0 = new List<string>();
            IList<string> pattern_SmallBricks_1 = new List<string>();
            IList<string> pattern_SmallBricks_2 = new List<string>();
            IList<string> pattern_SmallBricks_3 = new List<string>();
            IList<string> color_SmallBricks_0 = new List<string>();
            IList<string> color_SmallBricks_1 = new List<string>();
            IList<string> color_SmallBricks_2 = new List<string>();
            IList<string> color_SmallBricks_3 = new List<string>();

            IList<string> pattern_BigBricks_0 = new List<string>();
            IList<string> pattern_BigBricks_1 = new List<string>();
            IList<string> pattern_BigBricks_2 = new List<string>();
            IList<string> pattern_BigBricks_3 = new List<string>();
            IList<string> color_BigBricks_0 = new List<string>();
            IList<string> color_BigBricks_1 = new List<string>();
            IList<string> color_BigBricks_2 = new List<string>();
            IList<string> color_BigBricks_3 = new List<string>();

            IList<string> pattern_Grass_0 = new List<string>();
            IList<string> pattern_Grass_1 = new List<string>();
            IList<string> pattern_Grass_2 = new List<string>();
            IList<string> pattern_Grass_3 = new List<string>();
            IList<string> color_Grass_0 = new List<string>();
            IList<string> color_Grass_1 = new List<string>();
            IList<string> color_Grass_2 = new List<string>();
            IList<string> color_Grass_3 = new List<string>();

            IList<string> pattern_Rocks_0 = new List<string>();
            IList<string> pattern_Rocks_1 = new List<string>();
            IList<string> pattern_Rocks_2 = new List<string>();
            IList<string> pattern_Rocks_3 = new List<string>();
            IList<string> color_Rocks_0 = new List<string>();
            IList<string> color_Rocks_1 = new List<string>();
            IList<string> color_Rocks_2 = new List<string>();
            IList<string> color_Rocks_3 = new List<string>();

            IList<string> pattern_Diamond_0 = new List<string>();
            IList<string> pattern_Diamond_1 = new List<string>();
            IList<string> pattern_Diamond_2 = new List<string>();
            IList<string> pattern_Diamond_3 = new List<string>();
            IList<string> color_Diamond_0 = new List<string>();
            IList<string> color_Diamond_1 = new List<string>();
            IList<string> color_Diamond_2 = new List<string>();
            IList<string> color_Diamond_3 = new List<string>();

            IList<string> pattern_TestSquare_0 = new List<string>();
            IList<string> pattern_TestSquare_1 = new List<string>();
            IList<string> pattern_TestSquare_2 = new List<string>();
            IList<string> pattern_TestSquare_3 = new List<string>();
            IList<string> color_TestSquare_0 = new List<string>();
            IList<string> color_TestSquare_1 = new List<string>();
            IList<string> color_TestSquare_2 = new List<string>();
            IList<string> color_TestSquare_3 = new List<string>();



            // ------ Enemy Ladybug
            IList<string> pattern_EnemyLadybug_Left_0 = new List<string>();
            IList<string> pattern_EnemyLadybug_Left_1 = new List<string>();
            IList<string> pattern_EnemyLadybug_Left_2 = new List<string>();
            IList<string> pattern_EnemyLadybug_Left_3 = new List<string>();

            IList<string> pattern_EnemyLadybug_Right_0 = new List<string>();
            IList<string> pattern_EnemyLadybug_Right_1 = new List<string>();
            IList<string> pattern_EnemyLadybug_Right_2 = new List<string>();
            IList<string> pattern_EnemyLadybug_Right_3 = new List<string>();

            // Colors are the same for both left and right positions of the character
            IList<string> color_EnemyLadybug_0 = new List<string>();
            IList<string> color_EnemyLadybug_1 = new List<string>();
            IList<string> color_EnemyLadybug_2 = new List<string>();
            IList<string> color_EnemyLadybug_3 = new List<string>();



            // ------ Enemy Snail
            IList<string> pattern_EnemySnail_Left_0 = new List<string>();
            IList<string> pattern_EnemySnail_Left_1 = new List<string>();
            IList<string> pattern_EnemySnail_Left_2 = new List<string>();
            IList<string> pattern_EnemySnail_Left_3 = new List<string>();

            IList<string> pattern_EnemySnail_Right_0 = new List<string>();
            IList<string> pattern_EnemySnail_Right_1 = new List<string>();
            IList<string> pattern_EnemySnail_Right_2 = new List<string>();
            IList<string> pattern_EnemySnail_Right_3 = new List<string>();

            // Colors are the same for both left and right positions of the character
            IList<string> color_EnemySnail_0 = new List<string>();
            IList<string> color_EnemySnail_1 = new List<string>();
            IList<string> color_EnemySnail_2 = new List<string>();
            IList<string> color_EnemySnail_3 = new List<string>();


            // old code:
            GoPenguin.Tiles.Bg_Black.Load(out patternBgBlack, out colorBgBlack);
            GoPenguin.Tiles.Bg_Bricks_Small.Load(out pattern_SmallBricks_0, out color_SmallBricks_0, out pattern_SmallBricks_1, out color_SmallBricks_1, out pattern_SmallBricks_2, out color_SmallBricks_2, out pattern_SmallBricks_3, out color_SmallBricks_3);

            GoPenguin.Tiles.Bg_Bricks_Big.LoadFromTinySpriteBackup(out pattern_BigBricks_0, out color_BigBricks_0, out pattern_BigBricks_1, out color_BigBricks_1, out pattern_BigBricks_2, out color_BigBricks_2, out pattern_BigBricks_3, out color_BigBricks_3);
            GoPenguin.Tiles.Bg_Grass.LoadFromTinySpriteBackup(out pattern_Grass_0, out color_Grass_0, out pattern_Grass_1, out color_Grass_1, out pattern_Grass_2, out color_Grass_2, out pattern_Grass_3, out color_Grass_3);
            GoPenguin.Tiles.Bg_Rocks.LoadFromTinySpriteBackup(out pattern_Rocks_0, out color_Rocks_0, out pattern_Rocks_1, out color_Rocks_1, out pattern_Rocks_2, out color_Rocks_2, out pattern_Rocks_3, out color_Rocks_3);
            GoPenguin.Tiles.Bg_Diamond.LoadFromTinySpriteBackup(out pattern_Diamond_0, out color_Diamond_0, out pattern_Diamond_1, out color_Diamond_1, out pattern_Diamond_2, out color_Diamond_2, out pattern_Diamond_3, out color_Diamond_3);
            GoPenguin.Tiles.Bg_TestSquare.LoadFromTinySpriteBackup(out pattern_TestSquare_0, out color_TestSquare_0, out pattern_TestSquare_1, out color_TestSquare_1, out pattern_TestSquare_2, out color_TestSquare_2, out pattern_TestSquare_3, out color_TestSquare_3);

            GoPenguin.Tiles.Enemy_Ladybug_Left.LoadFromTinySpriteBackup(out pattern_EnemyLadybug_Left_0, out color_EnemyLadybug_0, out pattern_EnemyLadybug_Left_1, out color_EnemyLadybug_1, out pattern_EnemyLadybug_Left_2, out color_EnemyLadybug_2, out pattern_EnemyLadybug_Left_3, out color_EnemyLadybug_3);
            GoPenguin.Tiles.Enemy_Ladybug_Right.LoadFromTinySpriteBackup(out pattern_EnemyLadybug_Right_0, out color_EnemyLadybug_0, out pattern_EnemyLadybug_Right_1, out color_EnemyLadybug_1, out pattern_EnemyLadybug_Right_2, out color_EnemyLadybug_2, out pattern_EnemyLadybug_Right_3, out color_EnemyLadybug_3);

            GoPenguin.Tiles.Enemy_Snail_Left.LoadFromTinySpriteBackup(out pattern_EnemySnail_Left_0, out color_EnemySnail_0, out pattern_EnemySnail_Left_1, out color_EnemySnail_1, out pattern_EnemySnail_Left_2, out color_EnemySnail_2, out pattern_EnemySnail_Left_3, out color_EnemySnail_3);
            GoPenguin.Tiles.Enemy_Snail_Right.LoadFromTinySpriteBackup(out pattern_EnemySnail_Right_0, out color_EnemySnail_0, out pattern_EnemySnail_Right_1, out color_EnemySnail_1, out pattern_EnemySnail_Right_2, out color_EnemySnail_2, out pattern_EnemySnail_Right_3, out color_EnemySnail_3);



            // Save a .png file for each tile (will be used on Tiled map editor)
            SaveTilePngImage("Bricks small", pattern_SmallBricks_0, color_SmallBricks_0, pattern_SmallBricks_1, color_SmallBricks_1, pattern_SmallBricks_2, color_SmallBricks_2, pattern_SmallBricks_3, color_SmallBricks_3);
            SaveTilePngImage("Bricks big", pattern_BigBricks_0, color_BigBricks_0, pattern_BigBricks_1, color_BigBricks_1, pattern_BigBricks_2, color_BigBricks_2, pattern_BigBricks_3, color_BigBricks_3);
            SaveTilePngImage("Grass", pattern_Grass_0, color_Grass_0, pattern_Grass_1, color_Grass_1, pattern_Grass_2, color_Grass_2, pattern_Grass_3, color_Grass_3);
            SaveTilePngImage("Rocks", pattern_Rocks_0, color_Rocks_0, pattern_Rocks_1, color_Rocks_1, pattern_Rocks_2, color_Rocks_2, pattern_Rocks_3, color_Rocks_3);
            SaveTilePngImage("Diamond", pattern_Diamond_0, color_Diamond_0, pattern_Diamond_1, color_Diamond_1, pattern_Diamond_2, color_Diamond_2, pattern_Diamond_3, color_Diamond_3);


            // TODO: Fix these numbers, all of them are wrong, as the small bricks now are 24 tiles, not 48

            // Tile pattern # 49    bg              --> top left
            // Tile pattern # 57    top left        --> top right
            // Tile pattern # 65    top right       --> bg
            // Tile pattern # 73    top right       --> top left
            // Tile pattern # 81    bg              --> bottom left
            // Tile pattern # 89    bottom left     --> bottom right
            // Tile pattern # 97    bottom right    --> bg
            // Tile pattern # 105   bottom right    --> bottom left
            //builder.CreateCompleteSetOfTilesForScrolling(patternBgBlack,
            //    pattern_BigBricks_0, pattern_BigBricks_1, pattern_BigBricks_2, pattern_BigBricks_3,
            //    color_BigBricks_0, color_BigBricks_1, color_BigBricks_2, color_BigBricks_3,
            //    "BigBricks");

            // Tile pattern # 113   bg              --> top left
            // Tile pattern # 121   top left        --> top right
            // Tile pattern # 129   top right       --> bg
            // Tile pattern # 137   top right       --> top left
            // Tile pattern # 145   bg              --> bottom left
            // Tile pattern # 153   bottom left     --> bottom right
            // Tile pattern # 161   bottom right    --> bg
            // Tile pattern # 169   bottom right    --> bottom left
            builder.CreateCompleteSetOfTilesForScrolling(patternBgBlack,
                pattern_Grass_0, pattern_Grass_1, pattern_Grass_2, pattern_Grass_3,
                color_Grass_0, color_Grass_1, color_Grass_2, color_Grass_3,
                "Grass");

            // Tile pattern # 177   bg              --> top left
            // Tile pattern # 185   top left        --> top right
            // Tile pattern # 193   top right       --> bg
            // Tile pattern # 201   top right       --> top left
            // Tile pattern # 209   bg              --> bottom left
            // Tile pattern # 217   bottom left     --> bottom right
            // Tile pattern # 225   bottom right    --> bg
            // Tile pattern # 233   bottom right    --> bottom left
            builder.CreateCompleteSetOfTilesForScrolling(patternBgBlack,
                pattern_Rocks_0, pattern_Rocks_1, pattern_Rocks_2, pattern_Rocks_3,
                color_Rocks_0, color_Rocks_1, color_Rocks_2, color_Rocks_3,
                "Rocks");

            builder.CreateCompleteSetOfTilesForScrolling(patternBgBlack,
                pattern_Diamond_0, pattern_Diamond_1, pattern_Diamond_2, pattern_Diamond_3,
                color_Diamond_0, color_Diamond_1, color_Diamond_2, color_Diamond_3,
                "Diamonds");

            builder.CreateCompleteSetOfTilesForScrolling(patternBgBlack,
                pattern_TestSquare_0, pattern_TestSquare_1, pattern_TestSquare_2, pattern_TestSquare_3,
                color_TestSquare_0, color_TestSquare_1, color_TestSquare_2, color_TestSquare_3,
                "TestSquare");

            builder.CreateCompleteSetOfTilesForScrolling_Enemy(patternBgBlack,
                pattern_EnemyLadybug_Left_0, pattern_EnemyLadybug_Left_1, pattern_EnemyLadybug_Left_2, pattern_EnemyLadybug_Left_3,
                color_EnemyLadybug_0, color_EnemyLadybug_1, color_EnemyLadybug_2, color_EnemyLadybug_3,
                "EnemyLadybug_Left");

            builder.CreateCompleteSetOfTilesForScrolling_Enemy(patternBgBlack,
                pattern_EnemyLadybug_Right_0, pattern_EnemyLadybug_Right_1, pattern_EnemyLadybug_Right_2, pattern_EnemyLadybug_Right_3,
                color_EnemyLadybug_0, color_EnemyLadybug_1, color_EnemyLadybug_2, color_EnemyLadybug_3,
                "EnemyLadybug_Right");

            builder.CreateCompleteSetOfTilesForScrolling_Enemy(patternBgBlack,
                pattern_EnemySnail_Left_0, pattern_EnemySnail_Left_1, pattern_EnemySnail_Left_2, pattern_EnemySnail_Left_3,
                color_EnemySnail_0, color_EnemySnail_1, color_EnemySnail_2, color_EnemySnail_3,
                "EnemySnail_Left");

            builder.CreateCompleteSetOfTilesForScrolling_Enemy(patternBgBlack,
                pattern_EnemySnail_Right_0, pattern_EnemySnail_Right_1, pattern_EnemySnail_Right_2, pattern_EnemySnail_Right_3,
                color_EnemySnail_0, color_EnemySnail_1, color_EnemySnail_2, color_EnemySnail_3,
                "EnemySnail_Right");

            // old code:
            #region Small bricks

            // Tile pattern # 1
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Black", "Small brick - top"));
            //builder.CreateTilesForScrolling(patternBgBlack, pattern_SmallBricks_0);

            // Tile pattern # 9
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Small brick - top", "Small brick - top"));
            //builder.CreateTilesForScrolling(pattern_SmallBricks_0, pattern_SmallBricks_1);

            // Tile pattern # 17
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Small brick - top", "Black"));
            //builder.CreateTilesForScrolling(pattern_SmallBricks_0, patternBgBlack);


            // Tile pattern # 25
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Black", "Small brick - bottom"));
            //builder.CreateTilesForScrolling(patternBgBlack, pattern_SmallBricks_2);

            // Tile pattern # 33
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Small brick - bottom", "Small brick - bottom"));
            //builder.CreateTilesForScrolling(pattern_SmallBricks_2, pattern_SmallBricks_3);

            // Tile pattern # 41
            //Console.WriteLine(String.Format("; -------- Tile transitions from {0} to {1}", "Small brick - bottom", "Black"));
            //builder.CreateTilesForScrolling(pattern_SmallBricks_2, patternBgBlack);

            #endregion


        }

        private static void SaveTilePngImage(string fileName,
            IList<string> pattern_0, IList<string> color_0, IList<string> pattern_1, IList<string> color_1,
            IList<string> pattern_2, IList<string> color_2, IList<string> pattern_3, IList<string> color_3)
        {
            using (Bitmap bmp = new Bitmap(16, 16))
            {
                using (Graphics grp = Graphics.FromImage(bmp))
                {
                    grp.Clear(Color.Black);
                }

                for (int y = 0; y < 16; y++)
                {
                    var patternLine = "";
                    var colorLine = "";
                    if (y < 8)
                    {
                        patternLine = pattern_0[y] + pattern_1[y];
                        colorLine = color_0[y];
                    }
                    else
                    {
                        patternLine = pattern_2[y - 8] + pattern_3[y - 8];
                        colorLine = color_2[y - 8];
                    }
                    colorLine = colorLine.Replace("0x", "");

                    for (int x = 0; x < 16; x++)
                    {
                        var bit = patternLine.Substring(x, 1);
                        var hexStr = "";
                        if (bit == "1") // foreground color
                        {
                            hexStr = colorLine.Substring(0, 1);
                        }
                        else // background color
                        {
                            hexStr = colorLine.Substring(1, 1);
                        }

                        var colorValue = Convert.ToInt32(hexStr, 16);
                        var color = ConvertMsxColorValueToColor(colorValue);
                        bmp.SetPixel(x, y, color);
                    }
                }

                bmp.Save(fileName + ".png", ImageFormat.Png);
            }
        }

        static Color ConvertMsxColorValueToColor(int colorValue)
        {
            switch (colorValue)
            {
                case 0:
                    return Color.FromArgb(0, 0, 0);
                case 1:
                    return Color.FromArgb(1, 1, 1);
                case 2:
                    return Color.FromArgb(62, 184, 73);
                case 3:
                    return Color.FromArgb(116, 208, 125);
                case 4:
                    return Color.FromArgb(89, 85, 224);
                case 5:
                    return Color.FromArgb(128, 118, 241);
                case 6:
                    return Color.FromArgb(185, 94, 81);
                case 7:
                    return Color.FromArgb(101, 219, 239);
                case 8:
                    return Color.FromArgb(219, 101, 89);
                case 9:
                    return Color.FromArgb(255, 137, 125);
                case 10:
                    return Color.FromArgb(204, 195, 94);
                case 11:
                    return Color.FromArgb(222, 208, 135);
                case 12:
                    return Color.FromArgb(58, 162, 65);
                case 13:
                    return Color.FromArgb(183, 102, 181);
                case 14:
                    return Color.FromArgb(204, 204, 204);
                case 15:
                    return Color.FromArgb(255, 255, 255);
                default:
                    return Color.Black;
            }
        }

        static void CreateTilesForPacific2()
        {
            IList<string> bg = new List<string>();
            IList<string> input = new List<string>();
            IList<string> input2 = new List<string>();
            IList<string> input3 = new List<string>();

            IList<string> bgColors = new List<string>();
            IList<string> inputColors = new List<string>();
            IList<string> input2Colors = new List<string>();
            IList<string> input3Colors = new List<string>();


            var builder = new TilesForVerticalScroll();



            #region sequence of 3 or more tiles (5 transitions)

            //Tiles.Pacific2.Bg_Sea.Load(out bg, out bgColors);
            //Tiles.Pacific2.Land_MidRight.Load(out input, out input2, out input3, out inputColors, out input2Colors, out input3Colors);

            //builder.CreateTilesForScrolling_Entering(input, bg);
            //builder.CreateTilesForScrolling_1(input2, input);
            //builder.CreateTilesForScrolling_1(input2, input2);
            //builder.CreateTilesForScrolling_1(input3, input2);
            //builder.CreateTilesForScrolling_Exiting(bg, input3);

            ////builder.CreateTilesForScrolling_Entering(inputColors, bgColors);
            ////builder.CreateTilesForScrolling_1(input2Colors, inputColors);
            ////builder.CreateTilesForScrolling_1(input2Colors, input2Colors);
            ////builder.CreateTilesForScrolling_1(input3Colors, input2Colors);
            ////builder.CreateTilesForScrolling_Exiting(bgColors, input3Colors);

            #endregion sequence of 3 or more tiles (5 transitions)


            #region single tile with repetition (3 transitions)

            //Tiles.Pacific2.Bg_Sea.Load(out bg, out bgColors);
            //Tiles.Pacific2.Land_Leftmost.Load(out input, out inputColors);

            //Tiles.Pacific2.Bg_Land.Load(out bg, out bgColors);
            //Tiles.Pacific2.Trees.Load(out input, out inputColors);

            //builder.CreateTilesForScrolling_Entering(input, bg);
            //builder.CreateTilesForScrolling_1(input, input);
            //builder.CreateTilesForScrolling_Exiting(bg, input);

            //builder.CreateTilesForScrolling_Entering(inputColors, bgColors);
            //builder.CreateTilesForScrolling_1(inputColors, inputColors);
            //builder.CreateTilesForScrolling_Exiting(bgColors, inputColors);

            #endregion single tile with repetition (3 transitions)


            #region single tile without repetition (2 transitions)

            Pacific2.Tiles.Bg_Land.Load(out bg, out bgColors);
            Pacific2.Tiles.Rocks.Load(out input, out inputColors);

            //builder.CreateTilesForScrolling_Entering(input, bg);
            //builder.CreateTilesForScrolling_Exiting(bg, input);

            builder.CreateTilesForScrolling_Entering(inputColors, bgColors);
            builder.CreateTilesForScrolling_Exiting(bgColors, inputColors);

            #endregion single tile without repetition (2 transitions)
        }

        static string MakeUnrolledCommands(string command, int number)
        {
            var output = "";
            for (int i = 0; i < number; i++)
            {
                output += command + " ";
            }

            return output;
        }

        static void PocMegaROM()
        {
            var text = "\torg	8000h,0BFFFh	; page {0}" + "\n\r" +
                        "\tdb \"Text from segment {0}\",LF,CR,0" + "\n\r" +
                        "\tds PageSize -($ -8000h),255" + "\n\r";

            Console.WriteLine();

            for (int i = 9; i <= 255; i++)
            {
                Console.WriteLine(String.Format(text, i));
            }

            return;
        }



        // left side of road
        //From (111, 63) to (0, 90)
        //From (111, -2) to (0, ?)
        static void CalcPositionsPseudo3DEffect()
        {
            var xOrigin = 111;
            var yOrigin = 63;
            var xDest = 0;
            var yDest = 90;

            decimal step = (decimal)(xOrigin - xDest) / (decimal)(yDest - yOrigin + 0);
            decimal x = xOrigin;
            for (var y = yOrigin; y <= yDest; y++)
            {
                Console.WriteLine("db " + Math.Round(x) + "         ; x coord for line " + (y - yOrigin));
                x -= step;
            }
        }


        /// <summary>
        /// Read all names table and add an offset
        /// </summary>
        static void NameTableWithOffset()
        {
            var inputFilename = "screen1.nt2";
            var outputFilename = "screen joined.nt2";
            var offset = 76;

            var bytesInput = File.ReadAllBytes(inputFilename);

            var bytesOutput = new List<byte>();


            foreach (var byteInput in bytesInput)
            {
                bytesOutput.Add((byte)(byteInput + offset));
            }

            File.WriteAllBytes(outputFilename, bytesOutput.ToArray());

            Console.WriteLine("OK");
        }


        /// <summary>
        /// Read all color table separating each byte in two nibbles and converting color value from "x" to "y'
        /// </summary>
        static void ConvertColorTable()
        {
            var inputFilename = "screen.ct2";
            var outputFilename = "screen converted.ct2";

            var bytesInput = File.ReadAllBytes(inputFilename);

            var bytesOutput = new List<byte>();

            foreach (var byteInput in bytesInput)
            {
                var highNibble = (byteInput & 0b11110000) >> 4;

                var outputHighNibble = ReplaceNibble(highNibble) << 4;

                var lowNibble = (byteInput & 0b00001111);

                var outputLowNibble = ReplaceNibble(lowNibble);

                var byteOutput = outputHighNibble | outputLowNibble;

                bytesOutput.Add((byte)byteOutput);
            }

            File.WriteAllBytes(outputFilename, bytesOutput.ToArray());

            Console.WriteLine("OK");
        }

        static int ReplaceNibble(int nibble)
        {
            switch (nibble)
            {
                // Frame #1
                //case 7:
                //    return 14;
                //case 13:
                //    return 15;


                // Frame #2
                case 15:
                    return 8;

                case 8:
                    return 15;

                case 2:
                    return 10;

                case 10:
                    return 2;

                case 7:
                    return 15;
                case 13:
                    return 14;


                default:
                    return nibble;
                    //break;
            }

        }
    }
}
